almost_divisible_real64 – MPAS Dynamical Core
almost_divisible_real64 Function
12 statements
Source File
private pure elemental function almost_divisible_real64(a, b) result(almost_divisible)
Uses
iso_fortran_env
Test if a is divisible by b, where a and b are both reals. (KCW, 2024-05-25)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: a
real(kind=real64), intent(in) :: b
Return Value logical
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=real64), private :: error_tolerance
Source Code
    pure elemental function almost_divisible_real64(a, b) result(almost_divisible)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: a, b
        logical :: almost_divisible
        real(real64) :: error_tolerance
        error_tolerance = epsilon(1.0_real64) * max(abs(a), abs(b))
        if (almost_equal(mod(abs(a), abs(b)), 0.0_real64, absolute_tolerance=error_tolerance) .or. &
            almost_equal(mod(abs(a), abs(b)), abs(b), absolute_tolerance=error_tolerance)) then
            almost_divisible = .true.
            return
        end if
        almost_divisible = .false.
    end function almost_divisible_real64
Call graph
almost_divisible_real64 calls almost_equal
almost_equal calls almost_equal_real32, almost_equal_real64
almost_divisible calls almost_divisible_real64
dyn_mpas_init_phase4 calls almost_divisible
dyn_init calls dyn_mpas_init_phase4, dyn_init