clamp_int64 – MPAS Dynamical Core
clamp_int64 Function
6 statements
Source File
private pure elemental function clamp_int64(x, xmin, xmax) result(clamp)
Uses
iso_fortran_env
Clamp/Limit the value of x to the range of [xmin, xmax], where x, xmin, and xmax are all integers. No check is performed to ensure xmin < xmax. (KCW, 2025-07-16)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x
integer(kind=int64), intent(in) :: xmin
integer(kind=int64), intent(in) :: xmax
Return Value integer(kind=int64)
Called by
Source Code
    pure elemental function clamp_int64(x, xmin, xmax) result(clamp)
        use, intrinsic :: iso_fortran_env, only: int64
        integer(int64), intent(in) :: x, xmin, xmax
        integer(int64) :: clamp
        clamp = max(min(x, xmax), xmin)
    end function clamp_int64
Call graph
clamp calls clamp_int64
dyn_mpas_init_phase1 calls clamp
split calls clamp
dyn_readnl calls dyn_mpas_init_phase1, dyn_readnl
dynamics_to_physics_coupling calls update_shared_variables, dynamics_to_physics_coupling
tokenize_into_first_last calls split
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
parse_stream_name calls tokenize
stepon_timestep_init calls dynamics_to_physics_coupling
tokenize_into_tokens_separator calls tokenize
dyn_mpas_init_stream_with_pool calls parse_stream_name
dyn_mpas_read_write_stream calls parse_stream_name, dyn_mpas_init_stream_with_pool
dyn_init calls dyn_mpas_read_write_stream, dyn_init
dyn_variable_dump calls dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_read_write_stream, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
stepon_final calls dyn_final