dyn_mpas_compute_unit_vector – MPAS Dynamical Core
dyn_mpas_compute_unit_vector Subroutine
Michael Duda
15 January 2020
41 statements
Source File
private subroutine dyn_mpas_compute_unit_vector(self)
Uses
mpas_vector_operations
mpas_derived_types
This subroutine computes the local east and north unit vectors at all cells, storing the results in MPAS "mesh" pool as the "east" and "north" variables, respectively. It also computes the edge-normal unit vectors at all edges by calling mpas_initialize_vectors. Before calling this subroutine, MPAS "mesh" pool must contain the "latCell" and "lonCell" variables that are valid for all cells (not just solve cells), plus any additional variables that are required by mpas_initialize_vectors. For stand-alone MPAS, the whole deal is handled by init_dirs_forphys during physics initialization. However, MPAS as a dynamical core does not have physics, hence the existence of this subroutine. Ported and refactored for CAM-SIMA. (KCW, 2024-04-23)
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=rkind), private, pointer :: east(:,:)
integer, private :: i
real(kind=rkind), private, pointer :: latcell(:)
real(kind=rkind), private, pointer :: loncell(:)
type(mpas_pool_type), private, pointer :: mpas_pool
integer, private, pointer :: ncells
real(kind=rkind), private, pointer :: north(:,:)
real(kind=rkind), private, parameter :: pi = acos(-1.0_rkind)
character(len=*), private, parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_compute_unit_vector'
Source Code
    subroutine dyn_mpas_compute_unit_vector(self)
        ! Module(s) from MPAS.
        use mpas_derived_types, only: mpas_pool_type
        use mpas_vector_operations, only: mpas_initialize_vectors
        class(mpas_dynamical_core_type), intent(in) :: self
        character(*), parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_compute_unit_vector'
        real(rkind), parameter :: pi = acos(-1.0_rkind) ! Pi in native precision.
        integer :: i
        integer, pointer :: ncells
        real(rkind), pointer :: latcell(:), loncell(:)
        real(rkind), pointer :: east(:, :), north(:, :)
        type(mpas_pool_type), pointer :: mpas_pool
        call self % debug_print(log_level_debug, subname // ' entered')
        nullify(ncells)
        nullify(latcell, loncell)
        nullify(east, north)
        nullify(mpas_pool)
        ! Input.
        call self % get_variable_pointer(ncells, 'dim', 'nCells')
        call self % get_variable_pointer(latcell, 'mesh', 'latCell')
        call self % get_variable_pointer(loncell, 'mesh', 'lonCell')
        ! Output.
        call self % get_variable_pointer(east, 'mesh', 'east')
        call self % get_variable_pointer(north, 'mesh', 'north')
        call self % debug_print(log_level_info, 'Computing unit vectors')
        ! Make sure longitude values are within the range of [0, 2 * pi) according to MPAS mesh specifications.
        ! Although stand-alone MPAS can still accept longitude values outside this range without issues, CAM-SIMA is less
        ! tolerant about it. Note that there is a distinction between the `mod` and `modulo` intrinsic procedures.
        ! The former uses truncated division, while the latter uses floored division.
        loncell(:) = modulo(loncell, 2.0_rkind * pi)
        do i = 1, ncells
            east(1, i) = -sin(loncell(i))
            east(2, i) =  cos(loncell(i))
            east(3, i) =  0.0_rkind
            ! `r3_normalize` has been inlined below.
            east(1:3, i) = east(1:3, i) / sqrt(sum(east(1:3, i) * east(1:3, i)))
            north(1, i) = -cos(loncell(i)) * sin(latcell(i))
            north(2, i) = -sin(loncell(i)) * sin(latcell(i))
            north(3, i) =  cos(latcell(i))
            ! `r3_normalize` has been inlined below.
            north(1:3, i) = north(1:3, i) / sqrt(sum(north(1:3, i) * north(1:3, i)))
        end do
        nullify(ncells)
        nullify(latcell, loncell)
        nullify(east, north)
        call self % get_pool_pointer(mpas_pool, 'mesh')
        call mpas_initialize_vectors(mpas_pool)
        nullify(mpas_pool)
        call self % debug_print(log_level_debug, subname // ' completed')
    end subroutine dyn_mpas_compute_unit_vector
Call graph
dyn_mpas_compute_unit_vector calls mpas_initialize_vectors, get_variable_pointer, dyn_mpas_debug_print, dyn_mpas_get_pool_pointer
dyn_mpas_debug_print calls stringify
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_mpas_get_variable_pointer_c0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_c1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension
dyn_mpas_get_variable_pointer_i1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_dimension
dyn_mpas_get_variable_pointer_i2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_l0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r4 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r5 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
model_grid_init calls dyn_mpas_compute_unit_vector, model_grid_init