dyn_mpas_get_global_mesh_dimension – MPAS Dynamical Core
dyn_mpas_get_global_mesh_dimension Subroutine
Michael Duda
22 August 2019
51 statements
Source File
private subroutine dyn_mpas_get_global_mesh_dimension(self, ncells_global, nedges_global, nvertices_global, nvertlevels, ncells_max, nedges_max, sphere_radius)
Uses
mpas_dmpar
This subroutine returns global mesh dimensions, including: * Numbers of global mesh cells, edges, vertices, and vertical levels across all tasks. * Maximum numbers of mesh cells and edges/vertices among all tasks. * Sphere radius. Ported and refactored for CAM-SIMA. (KCW, 2024-03-25)
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
integer, intent(out), optional :: ncells_global
integer, intent(out), optional :: nedges_global
integer, intent(out), optional :: nvertices_global
integer, intent(out), optional :: nvertlevels
integer, intent(out), optional :: ncells_max
integer, intent(out), optional :: nedges_max
real(kind=rkind), intent(out), optional :: sphere_radius
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private, pointer :: maxedges_pointer
integer, private, pointer :: ncellssolve_pointer
integer, private, pointer :: nedgessolve_pointer
integer, private, pointer :: nverticessolve_pointer
integer, private, pointer :: nvertlevels_pointer
character(len=*), private, parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_global_mesh_dimension'
Source Code
    subroutine dyn_mpas_get_global_mesh_dimension(self, &
            ncells_global, nedges_global, nvertices_global, nvertlevels, ncells_max, nedges_max, &
            sphere_radius)
        ! Module(s) from MPAS.
        use mpas_dmpar, only: mpas_dmpar_max_int, mpas_dmpar_sum_int
        class(mpas_dynamical_core_type), intent(in) :: self
        integer, optional, intent(out) :: ncells_global, nedges_global, nvertices_global, nvertlevels, ncells_max, nedges_max
        real(rkind), optional, intent(out) :: sphere_radius
        character(*), parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_global_mesh_dimension'
        integer, pointer :: maxedges_pointer
        integer, pointer :: ncellssolve_pointer
        integer, pointer :: nedgessolve_pointer
        integer, pointer :: nverticessolve_pointer
        integer, pointer :: nvertlevels_pointer
        call self % debug_print(log_level_debug, subname // ' entered')
        nullify(maxedges_pointer)
        nullify(ncellssolve_pointer)
        nullify(nedgessolve_pointer)
        nullify(nverticessolve_pointer)
        nullify(nvertlevels_pointer)
        call self % debug_print(log_level_info, 'Inquiring global mesh dimensions')
        call self % get_variable_pointer(maxedges_pointer, 'dim', 'maxEdges')
        call self % get_variable_pointer(ncellssolve_pointer, 'dim', 'nCellsSolve')
        call self % get_variable_pointer(nedgessolve_pointer, 'dim', 'nEdgesSolve')
        call self % get_variable_pointer(nverticessolve_pointer, 'dim', 'nVerticesSolve')
        call self % get_variable_pointer(nvertlevels_pointer, 'dim', 'nVertLevels')
        if (present(ncells_global)) then
            call mpas_dmpar_sum_int(self % domain_ptr % dminfo, ncellssolve_pointer, ncells_global)
        end if
        if (present(nedges_global)) then
            call mpas_dmpar_sum_int(self % domain_ptr % dminfo, nedgessolve_pointer, nedges_global)
        end if
        if (present(nvertices_global)) then
            call mpas_dmpar_sum_int(self % domain_ptr % dminfo, nverticessolve_pointer, nvertices_global)
        end if
        ! Vertical levels are not decomposed.
        ! All tasks have the same number of vertical levels.
        if (present(nvertlevels)) then
            nvertlevels = nvertlevels_pointer
        end if
        if (present(ncells_max)) then
            call mpas_dmpar_max_int(self % domain_ptr % dminfo, ncellssolve_pointer, ncells_max)
        end if
        if (present(nedges_max)) then
            nedges_max = maxedges_pointer
        end if
        if (present(sphere_radius)) then
            sphere_radius = self % domain_ptr % sphere_radius
        end if
        nullify(maxedges_pointer)
        nullify(ncellssolve_pointer)
        nullify(nedgessolve_pointer)
        nullify(nverticessolve_pointer)
        nullify(nvertlevels_pointer)
        call self % debug_print(log_level_debug, subname // ' completed')
    end subroutine dyn_mpas_get_global_mesh_dimension
Call graph
dyn_mpas_get_global_mesh_dimension calls mpas_dmpar_max_int, mpas_dmpar_sum_int, get_variable_pointer, dyn_mpas_debug_print
dyn_mpas_debug_print calls stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_inquire_mesh_dimensions calls dyn_mpas_get_global_mesh_dimension, dyn_inquire_mesh_dimensions
model_grid_init calls dyn_inquire_mesh_dimensions, model_grid_init