dyn_grid_id – MPAS Dynamical Core
dyn_grid_id Module Function
13 statements
Source File
pure module function dyn_grid_id(name) Interface →
Uses
physics_grid
Helper function for returning grid id given its name. (KCW, 2024-03-27)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Return Value integer
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Source Code
    module pure function dyn_grid_id(name)
        ! Module(s) from CAM-SIMA.
        use physics_grid, only: phys_decomp
        character(*), intent(in) :: name
        integer :: dyn_grid_id
        integer :: i
        do i = 1, size(dyn_grid_name)
            if (trim(adjustl(dyn_grid_name(i))) == trim(adjustl(name))) then
                ! Grid ids count from `phys_decomp` + 1.
                ! This avoids id collisions between dynamics and physics grids.
                dyn_grid_id = phys_decomp + i
                return
            end if
        end do
        dyn_grid_id = 0
    end function dyn_grid_id
Call graph
dyn_grid_id calls dyn_grid_id
define_cam_grid calls dyn_grid_id
model_grid_init calls define_cam_grid, model_grid_init