dyn_mpas_compute_cell_relative_vorticity – MPAS Dynamical Core
dyn_mpas_compute_cell_relative_vorticity Subroutine
Kuan-Chih Wang
2025-04-12
35 statements
Source File
private subroutine dyn_mpas_compute_cell_relative_vorticity(self, cell_relative_vorticity)
Uses
dyn_mpas_procedures
MPAS uses staggered C-grid for spatial discretization, where relative vorticities are located at vertex points because wind vectors are located at edge points. However, physics schemes that use relative vorticities as input usually want them at cell points instead. This subroutine computes the relative vorticity at each cell point from its surrounding vertex points and returns the results.
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
real(kind=rkind), intent(out), allocatable :: cell_relative_vorticity(:,:)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=rkind), private, pointer :: areacell(:)
character(len=strkind), private :: cerr
integer, private :: i
integer, private :: ierr
integer, private :: k
real(kind=rkind), private, pointer :: kiteareasonvertex(:,:)
integer, private, pointer :: kiteforcell(:,:)
integer, private, pointer :: ncellssolve
integer, private, pointer :: nedgesoncell(:)
integer, private, pointer :: nvertlevels
character(len=*), private, parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_compute_cell_relative_vorticity'
integer, private, pointer :: verticesoncell(:,:)
real(kind=rkind), private, pointer :: vorticity(:,:)
Source Code
    subroutine dyn_mpas_compute_cell_relative_vorticity(self, cell_relative_vorticity)
        ! Module(s) from MPAS.
        use dyn_mpas_procedures, only: stringify
        class(mpas_dynamical_core_type), intent(in) :: self
        real(rkind), allocatable, intent(out) :: cell_relative_vorticity(:, :)
        character(*), parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_compute_cell_relative_vorticity'
        character(strkind) :: cerr
        integer :: i, k
        integer :: ierr
        integer, pointer :: ncellssolve, nvertlevels
        integer, pointer :: kiteforcell(:, :), nedgesoncell(:), verticesoncell(:, :)
        real(rkind), pointer :: areacell(:), kiteareasonvertex(:, :), vorticity(:, :)
        nullify(ncellssolve, nvertlevels)
        nullify(kiteforcell, nedgesoncell, verticesoncell)
        nullify(areacell, kiteareasonvertex, vorticity)
        ! Input.
        call self % get_variable_pointer(ncellssolve, 'dim', 'nCellsSolve')
        call self % get_variable_pointer(nvertlevels, 'dim', 'nVertLevels')
        call self % get_variable_pointer(kiteforcell, 'mesh', 'kiteForCell')
        call self % get_variable_pointer(nedgesoncell, 'mesh', 'nEdgesOnCell')
        call self % get_variable_pointer(verticesoncell, 'mesh', 'verticesOnCell')
        call self % get_variable_pointer(areacell, 'mesh', 'areaCell')
        call self % get_variable_pointer(kiteareasonvertex, 'mesh', 'kiteAreasOnVertex')
        call self % get_variable_pointer(vorticity, 'diag', 'vorticity')
        ! Output.
        allocate(cell_relative_vorticity(nvertlevels, ncellssolve), errmsg=cerr, stat=ierr)
        if (ierr /= 0) then
            call self % model_error('Failed to allocate cell_relative_vorticity' // new_line('') // &
                'Allocation returned with ' // stringify([ierr]) // ': ' // trim(adjustl(cerr)), &
                subname, __LINE__)
        end if
        do i = 1, ncellssolve
            do k = 1, nvertlevels
                cell_relative_vorticity(k, i) = regrid_from_vertex_to_cell(i, k, &
                    nedgesoncell, verticesoncell, kiteforcell, kiteareasonvertex, areacell, &
                    vorticity)
            end do
        end do
        nullify(ncellssolve, nvertlevels)
        nullify(kiteforcell, nedgesoncell, verticesoncell)
        nullify(areacell, kiteareasonvertex, vorticity)
    end subroutine dyn_mpas_compute_cell_relative_vorticity
Call graph
dyn_mpas_compute_cell_relative_vorticity calls get_variable_pointer, regrid_from_vertex_to_cell, stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool