dyn_run – MPAS Dynamical Core
dyn_run Module Subroutine
8 statements
Source File
module subroutine dyn_run() Interface →
Uses
cam_logfile
Run MPAS dynamical core to integrate the dynamical states with time. (KCW, 2024-07-11)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=*), private, parameter :: subname = 'dyn_comp::dyn_run'
Source Code
    module subroutine dyn_run()
        ! Module(s) from CAM-SIMA.
        use cam_logfile, only: debugout_debug, debugout_info
        character(*), parameter :: subname = 'dyn_comp::dyn_run'
        call dyn_debug_print(debugout_debug, subname // ' entered')
        call dyn_debug_print(debugout_info, 'Running MPAS dynamical core')
        ! MPAS dynamical core will run until the coupling time interval is reached.
        call mpas_dynamical_core % run()
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine dyn_run
Call graph
dyn_run calls dyn_debug_print, dyn_mpas_run, dyn_run
dyn_debug_print calls dyn_debug_print, stringify
dyn_mpas_run calls atm_compute_output_diagnostics, atm_do_timestep, mpas_advance_clock, mpas_get_clock_time, mpas_get_time, mpas_pool_shift_time_levels, mpas_set_timeinterval, get_variable_pointer, dyn_mpas_debug_print, dyn_mpas_get_pool_pointer, stringify
dyn_mpas_debug_print calls stringify
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_mpas_get_variable_pointer_c0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_c1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension
dyn_mpas_get_variable_pointer_i1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_dimension
dyn_mpas_get_variable_pointer_i2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_l0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r4 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r5 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
stepon_run3 calls dyn_run