dyn_mpas_get_variable_value_i0 – MPAS Dynamical Core
dyn_mpas_get_variable_value_i0 Subroutine
19 statements
Source File
private subroutine dyn_mpas_get_variable_value_i0(self, variable_value, pool_name, variable_name, time_level)
Uses
dyn_mpas_procedures
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
integer, intent(out), allocatable :: variable_value
character(len=*), intent(in) :: pool_name
character(len=*), intent(in) :: variable_name
integer, intent(in), optional :: time_level
Calls
Variables
Type Visibility Attributes Name Initial
character(len=strkind), private :: cerr
integer, private :: ierr
character(len=*), private, parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_variable_value_i0'
integer, private, pointer :: variable_pointer
Source Code
    subroutine dyn_mpas_get_variable_value_i0(self, variable_value, pool_name, variable_name, time_level)
        ! Module(s) from MPAS.
        use dyn_mpas_procedures, only: stringify
        class(mpas_dynamical_core_type), intent(in) :: self
        integer, allocatable, intent(out) :: variable_value
        character(*), intent(in) :: pool_name
        character(*), intent(in) :: variable_name
        integer, optional, intent(in) :: time_level
        character(*), parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_variable_value_i0'
        character(strkind) :: cerr
        integer, pointer :: variable_pointer
        integer :: ierr
        nullify(variable_pointer)
        call self % get_variable_pointer(variable_pointer, pool_name, variable_name, time_level=time_level)
        allocate(variable_value, source=variable_pointer, errmsg=cerr, stat=ierr)
        if (ierr /= 0) then
            call self % model_error('Failed to allocate variable "' // trim(adjustl(variable_name)) // '"' // new_line('') // &
                'Allocation returned with ' // stringify([ierr]) // ': ' // trim(adjustl(cerr)), &
                subname, __LINE__)
        end if
        nullify(variable_pointer)
    end subroutine dyn_mpas_get_variable_value_i0
Call graph
dyn_mpas_get_variable_value_i0 calls get_variable_pointer, stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool