dyn_mpas_get_local_mesh_dimension – MPAS Dynamical Core
dyn_mpas_get_local_mesh_dimension Subroutine
Kuan-Chih Wang
2024-05-09
57 statements
Source File
private subroutine dyn_mpas_get_local_mesh_dimension(self, ncells, ncells_solve, nedges, nedges_solve, nvertices, nvertices_solve, nvertlevels)
This subroutine returns local mesh dimensions, including: * Numbers of local mesh cells, edges, vertices, and vertical levels on each individual task, both with/without halo points.
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
integer, intent(out), optional :: ncells
integer, intent(out), optional :: ncells_solve
integer, intent(out), optional :: nedges
integer, intent(out), optional :: nedges_solve
integer, intent(out), optional :: nvertices
integer, intent(out), optional :: nvertices_solve
integer, intent(out), optional :: nvertlevels
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private, pointer :: ncells_pointer
integer, private, pointer :: ncellssolve_pointer
integer, private, pointer :: nedges_pointer
integer, private, pointer :: nedgessolve_pointer
integer, private, pointer :: nvertices_pointer
integer, private, pointer :: nverticessolve_pointer
integer, private, pointer :: nvertlevels_pointer
character(len=*), private, parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_local_mesh_dimension'
Source Code
    subroutine dyn_mpas_get_local_mesh_dimension(self, &
            ncells, ncells_solve, nedges, nedges_solve, nvertices, nvertices_solve, nvertlevels)
        class(mpas_dynamical_core_type), intent(in) :: self
        integer, optional, intent(out) :: ncells, ncells_solve, nedges, nedges_solve, nvertices, nvertices_solve, nvertlevels
        character(*), parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_local_mesh_dimension'
        integer, pointer :: ncells_pointer
        integer, pointer :: ncellssolve_pointer
        integer, pointer :: nedges_pointer
        integer, pointer :: nedgessolve_pointer
        integer, pointer :: nvertices_pointer
        integer, pointer :: nverticessolve_pointer
        integer, pointer :: nvertlevels_pointer
        call self % debug_print(log_level_debug, subname // ' entered')
        nullify(ncells_pointer)
        nullify(ncellssolve_pointer)
        nullify(nedges_pointer)
        nullify(nedgessolve_pointer)
        nullify(nvertices_pointer)
        nullify(nverticessolve_pointer)
        nullify(nvertlevels_pointer)
        call self % debug_print(log_level_info, 'Inquiring local mesh dimensions')
        call self % get_variable_pointer(ncells_pointer, 'dim', 'nCells')
        call self % get_variable_pointer(ncellssolve_pointer, 'dim', 'nCellsSolve')
        call self % get_variable_pointer(nedges_pointer, 'dim', 'nEdges')
        call self % get_variable_pointer(nedgessolve_pointer, 'dim', 'nEdgesSolve')
        call self % get_variable_pointer(nvertices_pointer, 'dim', 'nVertices')
        call self % get_variable_pointer(nverticessolve_pointer, 'dim', 'nVerticesSolve')
        call self % get_variable_pointer(nvertlevels_pointer, 'dim', 'nVertLevels')
        if (present(ncells)) then
            ncells = ncells_pointer                  ! Number of cells, including halo cells.
        end if
        if (present(ncells_solve)) then
            ncells_solve = ncellssolve_pointer       ! Number of cells, excluding halo cells.
        end if
        if (present(nedges)) then
            nedges = nedges_pointer                  ! Number of edges, including halo edges.
        end if
        if (present(nedges_solve)) then
            nedges_solve = nedgessolve_pointer       ! Number of edges, excluding halo edges.
        end if
        if (present(nvertices)) then
            nvertices = nvertices_pointer            ! Number of vertices, including halo vertices.
        end if
        if (present(nvertices_solve)) then
            nvertices_solve = nverticessolve_pointer ! Number of vertices, excluding halo vertices.
        end if
        ! Vertical levels are not decomposed.
        ! All tasks have the same number of vertical levels.
        if (present(nvertlevels)) then
            nvertlevels = nvertlevels_pointer
        end if
        nullify(ncells_pointer)
        nullify(ncellssolve_pointer)
        nullify(nedges_pointer)
        nullify(nedgessolve_pointer)
        nullify(nvertices_pointer)
        nullify(nverticessolve_pointer)
        nullify(nvertlevels_pointer)
        call self % debug_print(log_level_debug, subname // ' completed')
    end subroutine dyn_mpas_get_local_mesh_dimension
Call graph
dyn_mpas_get_local_mesh_dimension calls get_variable_pointer, dyn_mpas_debug_print
dyn_mpas_debug_print calls stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_inquire_mesh_dimensions calls dyn_mpas_get_local_mesh_dimension, dyn_inquire_mesh_dimensions
model_grid_init calls dyn_inquire_mesh_dimensions, model_grid_init