dyn_inquire_mesh_dimensions – MPAS Dynamical Core
dyn_inquire_mesh_dimensions Module Subroutine
17 statements
Source File
module subroutine dyn_inquire_mesh_dimensions() Interface →
Uses
cam_logfile
string_utils
dyn_comp
Inquire local and global mesh dimensions. Save them as protected module variables. (KCW, 2024-11-21)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=*), private, parameter :: subname = 'dyn_grid::dyn_inquire_mesh_dimensions'
Source Code
    module subroutine dyn_inquire_mesh_dimensions()
        ! Module(s) from CAM-SIMA.
        use cam_logfile, only: debugout_debug
        use dyn_comp, only: dyn_debug_print, mpas_dynamical_core
        use string_utils, only: stringify
        character(*), parameter :: subname = 'dyn_grid::dyn_inquire_mesh_dimensions'
        call dyn_debug_print(debugout_debug, subname // ' entered')
        call mpas_dynamical_core % get_local_mesh_dimension( &
            ncells, ncells_solve, nedges, nedges_solve, nvertices, nvertices_solve, nvertlevels)
        call mpas_dynamical_core % get_global_mesh_dimension( &
            ncells_global, nedges_global, nvertices_global, nvertlevels, ncells_max, nedges_max, &
            sphere_radius)
        call dyn_debug_print(debugout_debug, 'ncells_global    = ' // stringify([ncells_global]))
        call dyn_debug_print(debugout_debug, 'nedges_global    = ' // stringify([nedges_global]))
        call dyn_debug_print(debugout_debug, 'nvertices_global = ' // stringify([nvertices_global]))
        call dyn_debug_print(debugout_debug, 'nvertlevels      = ' // stringify([nvertlevels]))
        call dyn_debug_print(debugout_debug, 'ncells_max       = ' // stringify([ncells_max]))
        call dyn_debug_print(debugout_debug, 'nedges_max       = ' // stringify([nedges_max]))
        call dyn_debug_print(debugout_debug, 'sphere_radius    = ' // stringify([sphere_radius]))
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine dyn_inquire_mesh_dimensions
Call graph
dyn_inquire_mesh_dimensions calls dyn_debug_print, dyn_mpas_get_global_mesh_dimension, dyn_mpas_get_local_mesh_dimension, stringify, dyn_inquire_mesh_dimensions
dyn_debug_print calls dyn_debug_print, stringify
dyn_mpas_get_global_mesh_dimension calls mpas_dmpar_max_int, mpas_dmpar_sum_int, get_variable_pointer, dyn_mpas_debug_print
dyn_mpas_get_local_mesh_dimension calls get_variable_pointer, dyn_mpas_debug_print
dyn_mpas_debug_print calls stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
model_grid_init calls dyn_inquire_mesh_dimensions, model_grid_init