index_unique – MPAS Dynamical Core
index_unique Function
59 statements
Source File
public pure function index_unique(array)
Uses
iso_fortran_env
Return the index of unique elements in array, which can be any intrinsic data types, as an integer array. Please note that array must only have one dimension, and the unique elements are returned by their first occurrences in array. If array contains zero element or is of unsupported data types, an empty integer array is produced. For example, index_unique([1, 2, 3, 1, 2, 3, 4, 5]) returns [1, 2, 3, 7, 8]. (KCW, 2024-03-22)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: array(:)
Return Value integer, allocatable, (:)
Called by
Variables
Type Visibility Attributes Name Initial
character(len=:), private, allocatable :: array_c(:)
integer, private :: i
logical, private :: mask_unique(size(array))
integer, private :: n
Source Code
    pure function index_unique(array)
        use, intrinsic :: iso_fortran_env, only: int32, int64, real32, real64
        class(*), intent(in) :: array(:)
        integer, allocatable :: index_unique(:)
        character(:), allocatable :: array_c(:)
        integer :: i, n
        logical :: mask_unique(size(array))
        n = size(array)
        if (n == 0) then
            allocate(index_unique(0))
            return
        end if
        mask_unique = .false.
        select type (array)
            type is (character(*))
                ! Workaround for a bug in GNU Fortran >= 12. This is perhaps the manifestation of GCC Bugzilla Bug 100819.
                ! When a character string array is passed as the actual argument to an unlimited polymorphic dummy argument,
                ! its array index and length parameter are mishandled.
                allocate(character(len(array)) :: array_c(size(array)))
                array_c(:) = array(:)
                do i = 1, n
                    if (.not. any(array_c(i) == array_c .and. mask_unique)) then
                        mask_unique(i) = .true.
                    end if
                end do
                deallocate(array_c)
            type is (integer(int32))
                do i = 1, n
                    if (.not. any(array(i) == array .and. mask_unique)) then
                        mask_unique(i) = .true.
                    end if
                end do
            type is (integer(int64))
                do i = 1, n
                    if (.not. any(array(i) == array .and. mask_unique)) then
                        mask_unique(i) = .true.
                    end if
                end do
            type is (logical)
                do i = 1, n
                    if (.not. any((array(i) .eqv. array) .and. mask_unique)) then
                        mask_unique(i) = .true.
                    end if
                end do
            type is (real(real32))
                do i = 1, n
                    if (.not. any(array(i) == array .and. mask_unique)) then
                        mask_unique(i) = .true.
                    end if
                end do
            type is (real(real64))
                do i = 1, n
                    if (.not. any(array(i) == array .and. mask_unique)) then
                        mask_unique(i) = .true.
                    end if
                end do
            class default
                allocate(index_unique(0))
                return
        end select
        index_unique = pack([(i, i = 1, n)], mask_unique)
    end function index_unique
Call graph
dyn_mpas_define_scalar calls index_unique
parse_stream_name calls index_unique
dyn_init calls dyn_mpas_define_scalar, dyn_mpas_read_write_stream, dyn_init
dyn_mpas_init_stream_with_pool calls parse_stream_name
dyn_mpas_read_write_stream calls parse_stream_name, dyn_mpas_init_stream_with_pool
dyn_variable_dump calls dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_read_write_stream, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
stepon_final calls dyn_final