p_by_hypsometric_equation – MPAS Dynamical Core
p_by_hypsometric_equation Function
6 statements
Source File
public pure elemental function p_by_hypsometric_equation(constant_g, constant_rd, p1, z1, tv, z2) result(p2)
Uses
iso_fortran_env
Compute the pressure p2 at height z2 from the pressure p1 at height z1 by hypsometric equation. tv is the mean virtual temperature between z1 and z2. Essentially, . (KCW, 2024-07-02)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: constant_g
real(kind=real64), intent(in) :: constant_rd
real(kind=real64), intent(in) :: p1
real(kind=real64), intent(in) :: z1
real(kind=real64), intent(in) :: tv
real(kind=real64), intent(in) :: z2
Return Value real(kind=real64)
Called by
Source Code
    pure elemental function p_by_hypsometric_equation(constant_g, constant_rd, p1, z1, tv, z2) result(p2)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: constant_g, constant_rd, p1, z1, tv, z2
        real(real64) :: p2
        p2 = p1 * exp(-(z2 - z1) * constant_g / (constant_rd * tv))
    end function p_by_hypsometric_equation
Call graph
set_analytic_initial_condition calls set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta
dyn_init calls set_analytic_initial_condition, dyn_init