zu_of_dzw_real64 – MPAS Dynamical Core
zu_of_dzw_real64 Function
11 statements
Source File
private pure function zu_of_dzw_real64(dzw) result(zu)
Uses
iso_fortran_env
Compute the coordinates at u-wind levels zu from the differences in between w-wind levels dzw, where is the vertical coordinate, u-wind and w-wind levels are synonymous with layer midpoints and interfaces in MPAS, respectively. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: dzw(:)
Return Value real(kind=real64), (size(dzw))
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: k
real(kind=real64), private :: zw(size(dzw)+1)
Source Code
    pure function zu_of_dzw_real64(dzw) result(zu)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: dzw(:)
        real(real64) :: zu(size(dzw))
        integer :: k
        real(real64) :: zw(size(dzw) + 1)
        zw(:) = zw_of_dzw(dzw)
        do k = 1, size(zu)
            zu(k) = 0.5_real64 * (zw(k) + zw(k + 1))
        end do
    end function zu_of_dzw_real64
Call graph
zu_of_dzw_real64 calls zw_of_dzw
zw_of_dzw calls zw_of_dzw_real32, zw_of_dzw_real64
zu_of_dzw calls zu_of_dzw_real64
init_reference_pressure calls zu_of_dzw
model_grid_init calls init_reference_pressure, model_grid_init