clamp – MPAS Dynamical Core
clamp Interface
6 statements
Source File
public interface clamp
Calls
Called by
Module Procedures
private pure elemental function clamp_int32(x, xmin, xmax) result(clamp)
Clamp/Limit the value of x to the range of [xmin, xmax], where x, xmin, and xmax are all integers. No check is performed to ensure xmin < xmax. (KCW, 2025-07-16)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x
integer(kind=int32), intent(in) :: xmin
integer(kind=int32), intent(in) :: xmax
Return Value integer(kind=int32)
private pure elemental function clamp_int64(x, xmin, xmax) result(clamp)
Clamp/Limit the value of x to the range of [xmin, xmax], where x, xmin, and xmax are all integers. No check is performed to ensure xmin < xmax. (KCW, 2025-07-16)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x
integer(kind=int64), intent(in) :: xmin
integer(kind=int64), intent(in) :: xmax
Return Value integer(kind=int64)
private pure elemental function clamp_real32(x, xmin, xmax) result(clamp)
Clamp/Limit the value of x to the range of [xmin, xmax], where x, xmin, and xmax are all reals. No check is performed to ensure xmin < xmax. (KCW, 2025-07-16)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: x
real(kind=real32), intent(in) :: xmin
real(kind=real32), intent(in) :: xmax
Return Value real(kind=real32)
private pure elemental function clamp_real64(x, xmin, xmax) result(clamp)
Clamp/Limit the value of x to the range of [xmin, xmax], where x, xmin, and xmax are all reals. No check is performed to ensure xmin < xmax. (KCW, 2025-07-16)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: x
real(kind=real64), intent(in) :: xmin
real(kind=real64), intent(in) :: xmax
Return Value real(kind=real64)
Call graph
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
dyn_mpas_init_phase1 calls clamp
split calls clamp
dyn_readnl calls dyn_mpas_init_phase1, dyn_readnl
dynamics_to_physics_coupling calls update_shared_variables, dynamics_to_physics_coupling
tokenize_into_first_last calls split
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
parse_stream_name calls tokenize
stepon_timestep_init calls dynamics_to_physics_coupling
tokenize_into_tokens_separator calls tokenize
dyn_mpas_init_stream_with_pool calls parse_stream_name
dyn_mpas_read_write_stream calls parse_stream_name, dyn_mpas_init_stream_with_pool
dyn_init calls dyn_mpas_read_write_stream, dyn_init
dyn_variable_dump calls dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_read_write_stream, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
stepon_final calls dyn_final