dzw_of_rdzw – MPAS Dynamical Core
dzw_of_rdzw Interface
4 statements
Source File
public interface dzw_of_rdzw
Calls
Called by
Module Procedures
private pure elemental function dzw_of_rdzw_real32(rdzw) result(dzw)
Compute the differences in between w-wind levels dzw from the reciprocal differences in between w-wind levels rdzw, where is the vertical coordinate, and w-wind levels are synonymous with layer interfaces in MPAS. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: rdzw
Return Value real(kind=real32)
private pure elemental function dzw_of_rdzw_real64(rdzw) result(dzw)
Compute the differences in between w-wind levels dzw from the reciprocal differences in between w-wind levels rdzw, where is the vertical coordinate, and w-wind levels are synonymous with layer interfaces in MPAS. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: rdzw
Return Value real(kind=real64)
Call graph
dzw_of_rdzw calls dzw_of_rdzw_real32, dzw_of_rdzw_real64
init_reference_pressure calls dzw_of_rdzw
model_grid_init calls init_reference_pressure, model_grid_init