exner_function – MPAS Dynamical Core
exner_function Interface
4 statements
Source File
public interface exner_function
Calls
Called by
Module Procedures
private pure elemental function exner_function_of_cpd_p0_rd_p(constant_cpd, constant_p0, constant_rd, p) result(pi)
Compute the Exner function pi from the pressure p. Essentially, . (KCW, 2025-07-10)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: constant_cpd
real(kind=real64), intent(in) :: constant_p0
real(kind=real64), intent(in) :: constant_rd
real(kind=real64), intent(in) :: p
Return Value real(kind=real64)
private pure elemental function exner_function_of_kappa_p0_p(constant_kappa, constant_p0, p) result(pi)
Compute the Exner function pi from the pressure p. Essentially, . (KCW, 2025-08-16)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: constant_kappa
real(kind=real64), intent(in) :: constant_p0
real(kind=real64), intent(in) :: p
Return Value real(kind=real64)
Call graph
exner_function calls exner_function_of_cpd_p0_rd_p, exner_function_of_kappa_p0_p
dynamics_to_physics_coupling calls set_physics_state_external, dynamics_to_physics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling