tokenize – MPAS Dynamical Core
tokenize Interface
4 statements
Source File
public interface tokenize
Calls
Called by
Module Procedures
private pure subroutine tokenize_into_first_last(string, set, first, last)
Parse a string into tokens. Each character in set is a token delimiter. first is allocated with the lower bound equal to one and the upper bound equal to the number of tokens in string. Each element is assigned, in array element order, the starting position of each token in string, in the order found. last is allocated with the lower bound equal to one and the upper bound equal to the number of tokens in string. Each element is assigned, in array element order, the ending position of each token in string, in the order found. This subroutine implements the tokenize intrinsic procedure as defined in the Fortran 2023 language standard (Section 16.9.210). We implement it ourselves because the compiler support may take years to become widespread. (KCW, 2025-10-29)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: set
integer, intent(out), allocatable :: first(:)
integer, intent(out), allocatable :: last(:)
private pure subroutine tokenize_into_tokens_separator(string, set, tokens, separator)
Parse a string into tokens. Each character in set is a token delimiter. tokens is allocated with the lower bound equal to one and the upper bound equal to the number of tokens in string, and with character length equal to the length of the longest token. It contains the tokens in string. separator is allocated with the lower bound equal to one and the upper bound equal to one less than the number of tokens in string, and with character length equal to one. It contains the token delimiters in string. This subroutine implements the tokenize intrinsic procedure as defined in the Fortran 2023 language standard (Section 16.9.210). We implement it ourselves because the compiler support may take years to become widespread. (KCW, 2025-10-29)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: set
character(len=:), intent(out), allocatable :: tokens(:)
character(len=:), intent(out), optional, allocatable :: separator(:)
Call graph
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
tokenize_into_first_last calls split
tokenize_into_tokens_separator calls tokenize
split calls clamp
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
parse_stream_name calls tokenize
dyn_mpas_init_stream_with_pool calls parse_stream_name
dyn_mpas_read_write_stream calls parse_stream_name, dyn_mpas_init_stream_with_pool
dyn_init calls dyn_mpas_read_write_stream, dyn_init
dyn_variable_dump calls dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_read_write_stream, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
stepon_final calls dyn_final