zu_of_dzw – MPAS Dynamical Core
zu_of_dzw Interface
4 statements
Source File
public interface zu_of_dzw
Calls
Called by
Module Procedures
private pure function zu_of_dzw_real32(dzw) result(zu)
Compute the coordinates at u-wind levels zu from the differences in between w-wind levels dzw, where is the vertical coordinate, u-wind and w-wind levels are synonymous with layer midpoints and interfaces in MPAS, respectively. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: dzw(:)
Return Value real(kind=real32), (size(dzw))
private pure function zu_of_dzw_real64(dzw) result(zu)
Compute the coordinates at u-wind levels zu from the differences in between w-wind levels dzw, where is the vertical coordinate, u-wind and w-wind levels are synonymous with layer midpoints and interfaces in MPAS, respectively. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: dzw(:)
Return Value real(kind=real64), (size(dzw))
Call graph
zu_of_dzw calls zu_of_dzw_real32, zu_of_dzw_real64
zu_of_dzw_real32 calls zw_of_dzw
zu_of_dzw_real64 calls zw_of_dzw
zw_of_dzw calls zw_of_dzw_real32, zw_of_dzw_real64
init_reference_pressure calls zu_of_dzw
model_grid_init calls init_reference_pressure, model_grid_init