zw_of_dzw – MPAS Dynamical Core
zw_of_dzw Interface
4 statements
Source File
public interface zw_of_dzw
Calls
Called by
Module Procedures
private pure function zw_of_dzw_real32(dzw) result(zw)
Compute the coordinates at w-wind levels zw from the differences in between w-wind levels dzw, where is the vertical coordinate, and w-wind levels are synonymous with layer interfaces in MPAS. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: dzw(:)
Return Value real(kind=real32), (size(dzw)+1)
private pure function zw_of_dzw_real64(dzw) result(zw)
Compute the coordinates at w-wind levels zw from the differences in between w-wind levels dzw, where is the vertical coordinate, and w-wind levels are synonymous with layer interfaces in MPAS. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: dzw(:)
Return Value real(kind=real64), (size(dzw)+1)
Call graph
zw_of_dzw calls zw_of_dzw_real32, zw_of_dzw_real64
init_reference_pressure calls zw_of_dzw, zu_of_dzw
zu_of_dzw_real32 calls zw_of_dzw
zu_of_dzw_real64 calls zw_of_dzw
zu_of_dzw calls zu_of_dzw_real32, zu_of_dzw_real64
model_grid_init calls init_reference_pressure, model_grid_init